### ISSUE TITLE
Scammer selling your tool?

### ISSUE THREAD

**Issue by jonbarrow** [kwsch/png2bclim#4]
Not sure where else to report this at, but it looks like someone has taken this software and is selling it for around $10 _per month as a subscription service_. They didn't even bother to change the software name or look. Unsure if you can actually proceed with the payment since I'm not risking that, but thought you should know.

The domain was registered back in November of 2021 and was updated November last year, so who knows how long it has been operating?

It appears that when trying to actually purchase the subscription the price changes to $75/m, but that's just an error. It's 75 Danish Krone which is about $10 USD

The website is https://www.kulitu.com/

Screenshots incase they change anything

![Screenshot from 2023-01-28 17-28-31](https://user-images.githubusercontent.com/27011796/215293984-8b0b66ec-9ba2-44cc-ba1d-15ef965835b5.png)
![Screenshot from 2023-01-28 17-28-47](https://user-images.githubusercontent.com/27011796/215293988-ab020602-fc0b-4574-a931-7f3b0c44388e.png)

![Screenshot from 2023-01-28 17-26-36](https://user-images.githubusercontent.com/27011796/215293910-c52aecad-fe43-470c-aca8-4f8376b10a5d.png)
![Screenshot from 2023-01-28 17-26-22](https://user-images.githubusercontent.com/27011796/215293928-08b88df5-2849-408c-ad86-bc16e11633c9.png)
![Screenshot from 2023-01-28 17-26-09](https://user-images.githubusercontent.com/27011796/215293931-9596f71a-0335-4792-a191-3628e0003e99.png)

**Comment by kwsch** [comment]
This tool hasn't been updated in nearly a decade, and is super niche and essentially obsolete compared to other tools developed.

Not sure why anyone would pay for this. Doubt they'll ever get a "sale" to offset the cost of registering & hosting the scam site.
The releases here only had <2,000 downloads, lol

**Comment by jonbarrow** [comment]
Oh, alright. My bad then

**Comment by kwsch** [comment]
No worries, thanks for bringing it to my attention! I don't think it's worth much effort investigating / contacting wordpress :P
Quite funny to see a dead tool hosted by a scammer, instead of a more popular/used tool.
